Add cron
AizuGeekDojo/EnterLeaveSystem pull request #145
Opened 2019-05-22 02:34 UTC by i80486dx2

退出し忘れた場合に、深夜に強制退出させるようにしました。

2019-05-22 02:35 UTC, wancom commented
Reference #94

2019-05-22 02:36 UTC, wancom approved these changes
![LGTM](https://lgtmoon.herokuapp.com/images/13694)

2019-05-22 03:43 UTC, wancom requested changes
退室のログを残さないといけないのでダメでした。

2019-05-22 03:55 UTC, wancom commented on cmd/utils/cron.go
> +		db.ForceLeave(d)
エラー握りつぶしてた

2019-05-22 03:56 UTC, nozo-moto commented on cmd/db/user.go
> +	_, err := db.Exec(`update users set isenter=0`)
```
row, err := db.Query(`SELECT * FROM users where isenter=1`)
if err != nil {
 panic(err)
}

if err != nil {
    log.Fatal(err)
}
defer rows.Close()

for rows.Next() {
    var (
        id   int64
        isenter bool
    )
    if err := rows.Scan(&id, &name); err != nil {
        log.Fatal(err)
    }
    
     AddLog(id)
}
```

2019-06-26 04:52 UTC, wancom approved these changes
自分で自分にLGTM貼りたくない…

2019-06-26 05:01 UTC, nozo-moto approved these changes
LGTM

2019-06-26 05:01 UTC, merged