delete panic
AizuGeekDojo/EnterLeaveSystem pull request #152
Opened 2019-07-01 07:44 UTC by i80486dx2

2019-07-01 07:48 UTC, wancom commented
Reference #144

2019-07-02 00:28 UTC, hatobus requested changes

2019-07-02 00:28 UTC, hatobus commented on cmd/handler/socket.go
> +			time.Sleep(60 * time.Second)
できれば

```
log.Printf("nfc reader error : %v\n", err)
```

とか書いておいて、どうしてそこでエラーが起きているかを表示するといいかもです。
このままだとここでエラーが起きていることがわからず、あとあとめんどくさくなると思うので... 🙇

2019-07-03 03:30 UTC, hatobus commented
- ログの追加
- WebSocket通じてフロントの方に伝える
2点を追加しておきました

2019-07-03 05:01 UTC, hatobus approved these changes

2019-07-03 05:13 UTC, wancom commented
不要なファイルを削除しました。
これからテストします。

2019-07-03 05:48 UTC, wancom requested changes
バグがあったので確認お願いします。

2019-07-03 05:48 UTC, wancom commented on cmd/handler/socket.go
> +			retbyte, err := json.Marshal(resdat)
Marshalする前にresdatのIsCardをfalseにしてください。
(途中でカードリーダーが抜けると最後の人の情報が送られる)

2019-07-08 04:38 UTC, wancom commented
Reference #144

2019-07-08 06:47 UTC, wancom commented
この前にisCardのチェックが必要でした。
直しておきます。
https://github.com/AizuGeekDojo/EnterLeaveSystem/blob/efb9bdb81d816b6ed6b6b4230d5d72b2f290aee7/front/src/components/top.vue#L76

2019-07-08 07:14 UTC, wancom approved these changes
上記の修正で正常に動くことを確認しました。
LGTMです。お疲れ様でした。

2019-07-08 07:21 UTC, hatobus approved these changes

2019-07-08 07:22 UTC, nozo-moto commented on cmd/handler/socket.go
> +				c.Close()
もしかして書き込み毎、WebSockerクローズしてる？
フロント側でWebSocketクローズされたら再接続するようになってるから、多分問題起きてないと思うけどフロント側にログでてると思う
コネクション切る必要ない気もするのでCloseいらないかもね

2019-07-08 07:24 UTC, wancom commented on cmd/handler/socket.go
> +				c.Close()
なるほど。確かにコネクション切らなければそのまま維持できるね。
消すか。

2019-07-08 07:29 UTC, nozo-moto approved these changes
LGTM

websocketのクローズは、正常時のメッセージ送信の時にも起きてる問題だし、ちょっと検証した方が良い気がするので別にissue作りましょ

2019-07-08 07:30 UTC, wancom commented
いや、正常時は画面遷移するので普通にコネクションを閉じたいかな。

2019-07-08 07:31 UTC, nozo-moto commented on cmd/handler/socket.go
> -				c.Close()
消すのはcloseだけで良いんじゃない？

2019-07-08 07:32 UTC, nozo-moto commented
なるほど、なら大丈夫そうです！！ 🙆‍♂

2019-07-08 07:32 UTC, wancom commented on cmd/handler/socket.go
> -				c.Close()
まさにそれで、やらかした＼

2019-07-08 07:40 UTC, nozo-moto approved these changes
LGTM！！お疲れ様でした！！

2019-07-08 07:50 UTC, wancom approved these changes
テストで正常に動くことを確認しました。
改めてLGTMです。

2019-07-09 04:20 UTC, merged