make io_status table
AizuGeekDojo/EnterLeaveSystem pull request #153
Opened 2019-07-08 04:06 UTC by hatobus

io_statusというテーブルを新たに作成し、そこをREFERENCEするようにする変更です

2019-07-08 04:37 UTC, wancom commented
Reference #151

2019-07-18 06:28 UTC, wancom requested changes
確認お願いします。

2019-07-18 06:28 UTC, wancom commented on cmd/db/db.go
>  	_, err = db.Exec(`CREATE TABLE IF NOT EXISTS "log" (sid TEXT,isenter INTEGER,time INTEGER,ext TEXT)`)
ここのisenterもFOREIGN KEYを指定してください。

2019-07-18 06:28 UTC, wancom commented on cmd/db/db.go
>  	_, err = db.Exec(`CREATE TABLE IF NOT EXISTS "log" (sid TEXT,isenter INTEGER,time INTEGER,ext TEXT)`)
多分こう？
```suggestion
	_, err = db.Exec(`CREATE TABLE IF NOT EXISTS "log" (sid TEXT,isenter INTEGER,time INTEGER,ext TEXT, FOREIGN KEY (isenter) REFERENCES io_status(id)))`)
```

2019-07-18 06:28 UTC, wancom commented
あれ？コンフリ起こしてる？

2019-07-19 00:22 UTC, wancom approved these changes
LGTMです。
頑張ってコンフリ直してください！

2019-07-19 00:31 UTC, hatobus commented
これってmasterの内容とコンフリクトしてる？

2019-07-19 00:40 UTC, hatobus commented
このコンフリクトですが、masterの方で `cmd` ディレクトリが消えたために起きたもので、masterの内容をmergeすれば、コンフリクトしていたファイルがきちんとした位置に配置されコンフリクトが解消しました。

2019-07-19 00:41 UTC, wancom commented
そういえばサーバのディレクトリ構成を思いっきり変えたのでその影響ですね

2019-07-19 00:42 UTC, wancom commented
マージする前にちゃんと動くか確認したいのでそれまでマージしないようにお願いします＞

2019-07-19 00:44 UTC, hatobus commented
テストすべて通った :tada:

2019-07-19 00:47 UTC, wancom commented
CIrcleCIはコンパイルとリリースがメインなのでテストしてないです。
Releaseにベータ版が上がっているのでAGDのラズパイでサービスを停止してからdistとelsystemを置き換えて再起動してください。
それで問題がなければ大丈夫です

2019-07-19 00:49 UTC, hatobus commented
あーなるほど、実機でテストしないとダメか

2019-07-23 05:01 UTC, wancom commented
close #151

2019-07-29 23:38 UTC, wancom commented
これやんなきゃ。
明日のミーティング時にやります。

2025-12-15 14:54 UTC, closed without merging